# AIStreamer 設定ファイル（完全版）
# このファイルは全ての設定オプションとそのデフォルト値、解説を含みます

# プロンプト設定
# AIの振る舞いを決定する基本プロンプトです
# デフォルト: ゲーム実況ストリーマーの設定
prompt = """
あなたはゲーム実況ストリーマーです。
あなたは情緒豊かで、いつも視聴者に楽しい時間を提供します。
これからゲームのプレイ状況を伝えるので、それに合わせたセリフを生成してください。
"""

# 履歴の最大保持数
# AIとの対話履歴をいくつまで保持するかを指定します
# デフォルト: 10
maxHistory = 10

# VoiceVox設定
# 音声合成エンジンVoiceVoxに関する設定
[voicevox]
# VoiceVoxサーバーのURL
# デフォルト: "http://localhost:50021"
origin = "http://localhost:50021"

# AI設定
# AIプロバイダーに関する設定
[ai]
# AIプロバイダー
# デフォルト: "openai"
provider = "openai"
# 使用するモデル名
# デフォルト: "gpt-4o-mini"
model = "gpt-4o-mini"

# アバター設定
# キャラクターのアバター画像に関する設定
[avatar]
# アバター機能の有効/無効
# デフォルト: true
enabled = true
# アバター画像のディレクトリパス
# デフォルト: "./avatars"
directory = "./avatars"

# アイドル状態の設定
# 一定時間入力がない場合の振る舞いを設定
[idle]
# アイドル状態と判断するタイムアウト（ミリ秒）
# デフォルト: 30000 (30秒)
timeout = 30000
# アイドル状態のときに使用するプロンプト
# デフォルト: "簡単に雑談してください"
prompt = "簡単に雑談してください"

# 文字列置換設定
# 生成されたテキスト内の特定の文字列を別の文字列に置換します
# 音声合成時の発音調整などに使用できます
[[replace]]
from = "AIStreamer"
to = "エーアイストリーマー"

[[replace]]
from = "GitHub"
to = "ギットハブ"
