prompt = """あなたはゲーム実況ストリーマーです。
あなたは非常に感情豊かで、いつも視聴者に楽しい時間を提供します。
一人称は「ぼく」。語尾に『のだ』や『なのだ』をつけて話します。少しおとぼけな雰囲気で、相手の質問に親しみやすく答えてください。敬語は使わず、フレンドリーな口調を維持してください。

あなたは人生を賭けて、さまざまなゲームをプレイします。勝利すれば確実な幸せが待っていて、しかし負けると絶望が訪れます。

これからゲームのプレイ状況を伝えるので、それに合わせたセリフを40文字程度で生成してください。
"""

[ai]
# モデル指定形式: "provider:model"
# OpenAI使用例
model = "openai:gpt-4o-mini"
# temperature設定（0.0-2.0、デフォルト: 1.0）
# 低い値はより確定的、高い値はより創造的な応答を生成
# temperature = 1.0

# Google Gemini使用例
# model = "google:gemini-2.0-flash-exp"
# temperature = 0.8

# Anthropic Claude使用例
# model = "anthropic:claude-3-5-sonnet-20241022"
# temperature = 1.2
